- hosts: deb_hosts
  tasks:
    - name: Update Debian hosts
      debian_update:
        update_cache: true
        debian_update: true
        upgrade: true
        dist_upgrade: false
        autoremove: true
      register: update_result

    - name: Show update results
      debug:
        var: update_result
